AWSTemplateFormatVersion: '2010-09-09'
Description: Create Lambda Function for Linking accounts with Spot.io
Parameters:
  S3Bucket:
    Description: The name of the bucket that contains your packaged source
    Type: String
    Default: spot-connect-account-cf
  S3Key:
    Description: The name of the ZIP package on the zip file
    Type: String
    Default: function.zip
  ModuleName:
    Description: The name of the program file
    Type: String
    Default: lambda_function
  OrgId:
    Description: "The AWS Organization ID (Can be found in Organization Service, ie: o-hkum3f12134)"
    Type: String
Resources:
  SpotNetAppCreateAccountFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        S3Bucket:
          Ref: S3Bucket
        S3Key:
          Ref: S3Key
      Handler:
        'Fn::Join':
          - ''
          - - Ref: ModuleName
            - .lambda_handler
      Role:
        'Fn::GetAtt':
          - SpotNetAppLambdaExecutionRole
          - Arn
      Runtime: python3.8
      Timeout: '60'
      FunctionName: SpotNetAppCreateAccountFunction
  SpotNetAppLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      RoleName: SpotNetAppLambdaExecutionRole
      Policies:
        - PolicyName: SpotNetAppLambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: WhitelistSpecificLambdaFunction
                Effect: Deny
                Action: '*'
                Resource: '*'
                Condition:
                  StringNotLike:
                    'aws:userid': '*:SpotNetAppCreateAccountFunction'
              - Sid: CreateLogGroup
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Effect: Allow
                Resource: '*'
              - Sid: AccessSSM
                Action:
                  - 'ssm:GetParameter'
                  - 'ssm:PutParameter'
                  - 'ssm:DeleteParameter'
                Effect: Allow
                Resource: 'arn:aws:ssm:*:*:parameter/Spot-*'
              - Effect: Allow
                Action:
                  - 'organizations:ListAccounts'
                  - 'organizations:DescribeOrganization'
                  - 'organizations:DescribeOrganizationalUnit'
                  - 'organizations:DescribeAccount'
                Resource: '*'
  LambdaResourcePolicy:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName:
        'Fn::GetAtt':
          - SpotNetAppCreateAccountFunction
          - Arn
      Principal: '*'
      PrincipalOrgID:
        Ref: OrgId
Outputs:
  LambdaARN:
    Description: The Lambda Function for Spot by NetApp
    Value:
      'Fn::GetAtt':
        - SpotNetAppCreateAccountFunction
        - Arn
